# -*- coding: utf-8 -*-
"""Credit cad Fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13y6MPCzf088lv1saEiMjfjnN1SeynVYp
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

credit_card_data =pd.read_csv('/content/sample_data/creditcard.csv')
credit_card_data.head()

credit_card_data.tail()

credit_card_data.info()

credit_card_data.isnull().sum()

## distribution of legit and fraudulant transactions
credit_card_data['Class'].value_counts()

## highly unbalanced
## o is legit transaction and 1 is fraudulant transaction

legit= credit_card_data[credit_card_data.Class==0]
fraud =credit_card_data[credit_card_data.Class==1]

print(legit.shape)
print(fraud.shape)

##statistical analysis

legit.Amount.describe()

fraud.Amount.describe()

##compare the values of two variable

credit_card_data.groupby('Class').mean()

## undersampleing
## built a sample data set containing similar distribution of legit transaction and fraudulant transaction

legit_sample = legit.sample(n=492)

## concating legit sample of 492 with fraud 492 transactions

new_dataset = pd.concat([legit_sample,fraud], axis=0) ## axis =0 connects it row by row

new_dataset.head()

new_dataset.describe()

new_dataset['Class'].value_counts()

new_dataset.groupby('Class').mean()

credit_card_data.groupby('Class').mean()

## spliting the data into features and tragets

feature =new_dataset.drop(columns='Class', axis=1)
target  = new_dataset['Class']

print(feature)

# split the data into train and test split

X_train,X_test,Y_train,Y_test = train_test_split(feature,target,test_size=0.2, stratify=target, random_state=2)

print(X_test.shape,Y_test)
print(X_train)

## model training

model =LogisticRegression(max_iter=10000)

## traing logoistic regresion model with training data
model.fit (X_train, Y_train)

## model evaluating by acuuracy score

X_train_prediction =model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print(f"Accuracy of traing data is :{training_data_accuracy}")

X_test_prediction =model.predict(X_test)
accuracy = accuracy_score(X_test_prediction,Y_test)

print(f"Accuracy of test data is :{accuracy}")

##### random forest
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier()

model2.fit(X_train, Y_train)

X_test_prediction = model2.predict(X_train)
Accuracy =accuracy_score(X_test_prediction,Y_train)

print(f"Accuracy of Train data By random forest :{Accuracy}")

model2.fit(X_test, Y_test)
Model2_predicted_value =model2.predict(X_test)
Accuracy =accuracy_score(Model2_predicted_value,Y_test)

print(f"Accuracy of Test data By random forest :{Accuracy}")